### ISSUE TITLE
如何画一个只能在已显示区域进行事件绑定的三角形

### ISSUE THREAD

**Issue by vortesnail** [vortesnail/blog#3]
# 如何画一个只能在已显示区域进行事件绑定的三角形

**前言:** 这个问题是去一家公司面试的时候，技术经理问到我的，我第一想法是用CSS中的`border`去画，但是我们现在的要求是在那个三角形区域，才能进行事件的绑定，比如：click事件，那`border`所用到的`transparent`仅仅是透明度为0，那个区域还是在的，这就无法完成特定区域的事件绑定。

### 1.先来试试border方法到底行不行吧！
Html:
```html
<div className="triangle"></div>
```
Css:
```css
.triangle {
  width: 0px;
  height: 0px;
  border-left: 50px solid yellow;
  border-right: 50px solid blue;
  border-top: 50px solid red;
  border-bottom: 50px solid black;
}
```

现在我们可以看到如下：
![image.png](https://cdn.nlark.com/yuque/0/2019/png/341314/1569304843030-58b8ee55-4af6-4320-b302-d7246c927976.png#align=left&display=inline&height=115&name=image.png&originHeight=230&originWidth=220&size=2783&status=done&width=110)
我们就选一个指向右边的箭头吧，修改Css样式：
Css:
```css
.triangle {
  width: 0px;
  height: 0px;
  border-left: 50px solid yellow;
  border-right: 50px solid transparent;
  border-top: 50px solid transparent;
  border-bottom: 50px solid transparent;
}
```

现在我们得到了想要的三角形（具体形状自行调整`border-size`就行）：
![image.png](https://cdn.nlark.com/yuque/0/2019/png/341314/1569304202197-e858b2fe-6eb3-44f0-83ee-ef56fd25f1c6.png#align=left&display=inline&height=117&name=image.png&originHeight=234&originWidth=204&size=2345&status=done&width=102)

接下来，我们给这个 `div` 添加一个 `onmouseover` 事件：
```javascript
const triangle = document.querySelector('.triangle');
triangle.addEventListener('mouseover', () => {
  console.log('你碰到我了！');
})
```

结果我们去测试的时候，不出所料地，透明的部分也会触发事件，如下所示：

![1.gif](https://cdn.nlark.com/yuque/0/2019/gif/341314/1569305261767-b68eb44c-907a-4249-ac11-4f528bba77d3.gif#align=left&display=inline&height=287&name=1.gif&originHeight=612&originWidth=862&size=215083&status=done&width=403)

那可咋办呢？？

### 2.换个思路，用遮罩！
这个思路很简单，但是面试官坐在面前的时候，却怎么也想不出来。。

#### step1: 我们先画三个矩形：
Html:
```html
<div class="rectangle-1"></div>
<div class="rectangle-2"></div>
<div class="rectangle-3"></div>
```
Css:
```css
.reactangle-container {
  position: relative;
}

.rectangle-mask1,
.rectangle-mask2 {
  width: 200px;
  height: 80px;
  position: absolute;
}

.rectangle-mask1 {
  top: 11px;
  left: -5px;
  transform: rotate(50deg);
  background-color: lightblue;
  z-index: 2;
}

.rectangle-mask2 {
  bottom: 11px;
  left: -5px;
  transform: rotate(-50deg);
  background-color: lightgreen;
  z-index: 2;
}

.rectangle-tri {
  width: 100px;
  height: 100px;
  background-color: lightcoral;
  z-index: 1;
}
```

得到如下图：
![image.png](https://cdn.nlark.com/yuque/0/2019/png/341314/1569306553233-60021a9f-5bee-4251-905d-f3e9d910cc03.png#align=left&display=inline&height=228&name=image.png&originHeight=456&originWidth=510&size=20920&status=done&width=255)
其中粉红的区域就是我们要的三角形区域，理论上你可以通过**两个或许多个矩形构建出你想要的任何三角形！**

#### step2: 进行绑定
那这个时候，我们怎么绑定事件到这个三角形上呢？
**思路:** 给 `rectangle-tri` 这个矩形绑定事件，也给 `rectangle-mask1` 和 `rectangle-mask2` 绑定事件，但是不做操作，这样的话，因为`rectangle-tri` 在最下面，移动非三角形区域的时候，触发的事件监听是另外两个遮罩矩形的事件。

```javascript
const reactangleContainer = document.querySelector('.reactangle-container');
const rectangleMask1 = reactangleContainer.querySelector('.rectangle-mask1');
const rectangleMask2 = reactangleContainer.querySelector('.rectangle-mask2');
const rectangleTri = reactangleContainer.querySelector('.rectangle-tri');

rectangleTri.addEventListener('mouseover', () => {
  console.log('你碰到我了！');
})

rectangleMask1.addEventListener('mouseover', () => {
	// 不做任何行为
})

rectangleMask2.addEventListener('mouseover', () => {
	// 不做任何行为
})
```

此时，特定的区域才有事件绑定了：
![2.gif](https://cdn.nlark.com/yuque/0/2019/gif/341314/1569308741394-74f5c1a1-bf58-4b4f-bff4-fe60455d1191.gif#align=left&display=inline&height=292&name=2.gif&originHeight=740&originWidth=1072&size=259173&status=done&width=423)

现在，我们怎么把这两个遮罩矩形去掉呢？？？？设置背景色为白色？那就是**自欺欺人**了
#### step3: 只显示三角形
**这里我真的还找不到方法啊，有哪位大佬能来说说吗？？？**

### 3.用CSS3中的clip-path试试吧！
> `clip-path` [CSS](https://developer.mozilla.org/zh-CN/docs/Web/CSS) 属性可以创建一个只有元素的部分区域可以显示的剪切区域。区域内的部分显示，区域外的隐藏。剪切区域是被引用内嵌的URL定义的路径或者外部svg的路径，或者作为一个形状例如[circle()](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle).。clip-path属性代替了现在已经弃用的剪切 [clip](https://developer.mozilla.org/en-US/docs/Web/CSS/clip)属性。

上看的引用出自MDN，我们只需要知道，这个属性可以让我们裁剪出想要的形状

基本形状裁剪：
```css
.clip-me {
  clip-path: inset();
  clip-path: circle();
  clip-path: ellipse();
  clip-path: polygon();
}
```
其中inset是矩形的剪切，circle是圆形的剪切，ellipse是椭圆的剪切，polygon是多边形的剪切。对于我们想要把矩形剪切成三角形，应该使用polygon这个语法。
Html:
```html
<div class="triangle"></div>
```
Css:
```css
.triangle {
  width: 100px;
  height: 100px;
  background-color: lightcoral;
  clip-path: polygon(0px 0px, 0px 100px, 100px 50px);
}
```

`clip-path: polygon(0px 0px, 0px 100px, 100px 50px);` 这句话意思是，根据坐标轴上确定的三个点来进行裁剪：(0px, 0px),(0px 100px),(100px, 50px) ,这三个点构成了一个我们如下三角形：
![image.png](https://cdn.nlark.com/yuque/0/2019/png/341314/1569309800990-6bf7efa6-6802-4fc9-93a6-0a3e5525a3bb.png#align=left&display=inline&height=109&name=image.png&originHeight=218&originWidth=240&size=2476&status=done&width=120)

现在我们可以来试试绑定事件好不好用来：

```javascript
const tri = document.querySelector('.triangle');
tri.addEventListener('mouseover', () => {
  console.log("你碰到我了！");
})
```

以下为测试结果：
![3.gif](https://cdn.nlark.com/yuque/0/2019/gif/341314/1569310112124-4d36eb7c-2fd4-4b7b-800b-28c041048510.gif#align=left&display=inline&height=317&name=3.gif&originHeight=740&originWidth=1072&size=157150&status=done&width=459)

我只能说，这个真是太好用了，不过这个属性兼容性会有些不好，酌情使用把！
